name: traffic-experiments
channels:
  - conda-forge
dependencies:
  - xorg-libxext
  - libglvnd-glx-cos7-x86_64
  - qt
  - cmake
  - eigen
  - boost
  - yaml-cpp
  - xeus-cling=>0.10.0
  - jupyterlab
  - python=3.6
  - pip
  - pyyaml
  - paho-mqtt
  - matplotlib
  - networkx
  - scipy
  - pip:
    - -r file:requirements.txt